name: Tests
on: [push]
jobs:
  automatic_tests:
  name: Automatic Tests
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Test 1 Output
    run: python3 find_lowest_number.py test1_input.txt test1_actual_output.txt
  - name: Test 1
    run: diff test1_expected.txt test1_actual_output.txt
  - name: Test 2 Output
    run: python3 find_lowest_number.py test2_input.txt test2_actual_output.txt
  - name: Test 2
    run: diff test2_expected.txt test2_actual_output.txt
  - name: Test 2 Output
    run: python3 find_lowest_number.py test3_input.txt test3_actual_output.txt
  - name: Test 2
    run: diff test3_expected.txt test3_actual_output.txt
